/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "sort.h"


void
sort_prog_1(char *host,int numbers[5])
{
	CLIENT *clnt;
	numarray  *result_1;
	numarray  sort_1_arg;
	int i;
	
#ifndef	DEBUG
	clnt = clnt_create (host, SORT_PROG, SORT_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	for(i=0;i<5;i++){
		sort_1_arg.numbers[i]=numbers[i];
	}
	result_1 = sort_1(&sort_1_arg, clnt);
	if (result_1 == (numarray *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("Sorted number sequence is\n");
		for(i=0;i<5;i++){
			// print the last sorted number without the ','
			if (i==4){	
				printf("%d\n",(result_1->numbers)[i]);
			}
			else{
				printf("%d , ",(result_1->numbers)[i]);
			}		
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	// if number of arguments are less than 7
	if (argc < 7) {
		printf("Less number of arguments\n");
		printf ("usage: %s server_host NUMBER NUMBER NUMBER NUMBER NUMBER\n", argv[0]);
		exit (1);
	}
	else if (argc >7){
		printf("Number of arguments exceeded\n");
		printf ("usage: %s server_host NUMBER NUMBER NUMBER NUMBER NUMBER\n", argv[0]);
	}
	host = argv[1];
	int numbers[5],i;
	for(i=0;i<5;i++){
		numbers[i]=atoi(argv[i+2]);
	}
	sort_prog_1 (host,numbers);
exit (0);
}
