/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "sort.h"

numarray *
sort_1_svc(numarray *argp, struct svc_req *rqstp)
{
	static numarray  result;
	printf("sort(%d,%d,%d,%d,%d) function is called\n",argp->numbers[0],argp->numbers[1],argp->numbers[2],argp->numbers[3],argp->numbers[4]);
	int i, key, j;
	   for (i = 1; i < 5; i++)
	   {
	       key = (argp->numbers)[i];
	       j = i-1;

	       /* Move elements of (argp->numbers)[0..i-1], that are
	          greater than key, to one position ahead
	          of their current position */
	       while (j >= 0 && (argp->numbers)[j] > key)
	       {
	           (argp->numbers)[j+1] = (argp->numbers)[j];
	           j = j-1;
	       }
	       (argp->numbers)[j+1] = key;
	   }
	result=*argp;   
	return &result;
}
