/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SORT_H_RPCGEN
#define _SORT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numarray {
	int numbers[5];
};
typedef struct numarray numarray;

#define SORT_PROG 0x23451111
#define SORT_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define sort 1
extern  numarray * sort_1(numarray *, CLIENT *);
extern  numarray * sort_1_svc(numarray *, struct svc_req *);
extern int sort_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sort 1
extern  numarray * sort_1();
extern  numarray * sort_1_svc();
extern int sort_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numarray (XDR *, numarray*);

#else /* K&R C */
extern bool_t xdr_numarray ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SORT_H_RPCGEN */
